gourmet/plugins/web_plugin/gourmetweb/urls.py
from django.conf.urls import patterns

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns(
    '',
    (r'^$','gourmetweb.recview.views.index'),
    (r'^sort/(?P<field>.*)/','gourmetweb.recview.views.sort'),
    (r'^search/(?P<term>.*)','gourmetweb.recview.views.search'),
    (r'^rec/do_search/','gourmetweb.recview.views.do_search'),
    (r'^rec/do_search_xhr/','gourmetweb.recview.views.do_search_xhr'),
    (r'^regexp/(?P<term>.*)','gourmetweb.recview.views.regexp'),
    (r'^rec/$','gourmetweb.recview.views.index'),
    (r'^rec/(?P<rec_id>\d*)/$','gourmetweb.recview.views.rec'),
    (r'^rec/(?P<rec_id>\d*)/(?P<mult>[\d.]*)$','gourmetweb.recview.views.rec'),
    (r'^shop/$','gourmetweb.recview.views.shop'),
    (r'^shop/(?P<rec_id>\d*)/$','gourmetweb.recview.views.shop'),
    (r'^shop/(?P<rec_id>\d*)/(?P<mult>[\d.]*)$','gourmetweb.recview.views.shop'),
    (r'^shop/remove/(?P<rec_id>\d*)/$','gourmetweb.recview.views.shop_remove'),
    (r'^shop/to_pantry/','gourmetweb.recview.views.shop_to_pantry'),
    (r'^shop/to_list/','gourmetweb.recview.views.shop_to_list'),
    (r'^rec/multiply/','gourmetweb.recview.views.multiply_rec'),
    (r'^img/(?P<rec_id>\d*)/$','gourmetweb.recview.views.img'),
    (r'^thumb/(?P<rec_id>\d*)/$','gourmetweb.recview.views.thumb'),
    (r'^rec/multiply_xhr/','gourmetweb.recview.views.multiply_rec_xhr'),
    (r'^js/(?P<path>.*)$','django.views.static.serve',{'document_root':'/home/tom/Projects/grecipe-manager/src/lib/plugins/web_plugin/gourmetweb/templates/'}),
    #(r'^shop/(?P<rec_id>\d*)/(?P<mult>\d)/$','gourmetweb.recview.views.shop'),
    # Example:
    # (r'^gourmet/', include('gourmet.foo.urls')),

    # Uncomment the admin/doc line below and add 'django.contrib.admindocs'
    # to INSTALLED_APPS to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # (r'^admin/', include(admin.site.urls)),
)

gourmet/plugins/web_plugin/gourmetweb/recview/models.py
from django.db import models

# Create your models here.

gourmet/plugins/web_plugin/gourmetweb/recview/views.py
from gettext import gettext as _
from django.http import HttpResponse, HttpResponseRedirect
from django import forms
from django.shortcuts import render_to_response
from django.template import Context, loader
import sys
import re
import gourmet.backends.db
import gourmet.shopping
import gourmet.recipeManager
from django.utils import simplejson


class MultiplierForm (forms.Form):
    yields = forms.FloatField(label='New Yield',min_value=0,required=False)
    multiplier = None
    #multiplier = forms.FloatField(label='x',min_value=0,required=False)

class NoYieldsMultiplierForm (forms.Form):
    multiplier = forms.FloatField(label='x',min_value=0,required=False)
    yields = None

class SearchForm (forms.Form):
    choices = {unicode(_('anywhere')):'anywhere',
               unicode(_('title')):'title',
               unicode(_('ingredient')):'ingredient',
               unicode(_('instructions')):'instructions',
               unicode(_('notes')):'modifications',
               unicode(_('category')):'category',
               unicode(_('cuisine')):'cuisine',
               unicode(_('source')):'source',}
    search_field = forms.CharField(max_length=100)
    regexp_field = forms.BooleanField(label='Use regexp')
    choice_field = forms.ChoiceField(label='Search in...',
                                     initial='anywhere',
                                     choices=choices.items()
                                     )

rd = gourmet.backends.db.get_database()

class MyShoppingList (gourmet.shopping.ShoppingList):

    def get_shopper (self, lst):
        return gourmet.recipeManager.DatabaseShopper(lst, rd)

slist = MyShoppingList()

def list_recs (view, default_search_values={},
               template='index.html'):
    sf = SearchForm()
    for k,v in default_search_values.items():
        print 'Set',k,'to',v
        sf.fields[k].initial = v
    return render_to_response(
        template,
        {'recs':[(rec,rd.get_cats(rec)) for rec in view],
         'form':sf
        }
        )

def index (request):
    return list_recs(rd.fetch_all(rd.recipe_table,deleted=False))

def sort (request, field):
    return list_recs(rd.fetch_all(rd.recipe_table,deleted=False,sort_by=[(field,1)]))

def do_search_xhr (request):
    if request.method == 'POST':
        form = SearchForm(request.POST)
        print 'Searching ',form.data['search_field']
        return search(request,form.data['search_field'],template='list.html')
    else:
        print 'Not a post!'


def do_search (request):
    if request.method == 'POST':
        form = SearchForm(request.POST)
        print 'Searching ',form.data['search_field']
        return search(request,form.data['search_field'])
    else:
        print 'Not a post!'

def search (request, term, template='index.html'):
    vw = rd.search_recipes(
        [{'column':'deleted','operator':'=','search':False},
         {'column':'anywhere',
          'operator':'LIKE',
          'search':'%'+term.replace('%','%%'+'%')+'%',
          }
         ]
        )
    print 'We got ',len(vw),'for "%s"'%term
    return list_recs(vw, default_search_values={
        'search_field':term,
        'regexp_field':False,
        'choice_field':'anywhere',
        },
                     template=template
                     )


def get_ings (rec_id, mult):
    ings = rd.order_ings(rd.get_ings(rec_id))
    formatted_ings = []
    for g,items in ings:
        formatted_items = []
        for item in items:
            strings = []
            amt,unit = rd.get_amount_and_unit(item,mult=mult)
            if amt: strings.append(amt)
            if unit: strings.append(unit)
            strings.append(item.item)
            if item.optional: strings.append(' (optional)')
            formatted_items.append(' '.join(strings))
        formatted_ings.append((g,formatted_items))
    return formatted_ings

def rec (request, rec_id, mult=1):
    mult = float(mult)
    rec = rd.get_rec(rec_id)
    formatted_ings = get_ings(rec_id,mult)
    def textify (t):
        if not t: return ''
        print 'textifying "%s"'%t
        return re.sub('\n','<br>',
                      re.sub('\n\n+','</p><p>','<p>%s</p>'%t.strip()))
    if rec.yields:
        print 'WITH YIELDS'
        mf = MultiplierForm()
    else:
        print 'WITHOUT YIELDS'
        mf = NoYieldsMultiplierForm()
    return render_to_response(
        'rec.html',
        {'rd':rd,
         'r':rec,
         'ings':formatted_ings,
         'cats':', '.join(rd.get_cats(rec)),
         'instructions':textify(rec.instructions),
         'notes':textify(rec.modifications),
         'mult':mult,
         'yields':(rec.yields and rec.yields * mult or None),
         'is_adjusted': (mult!=1),
         'multiplier_form':mf,
         }
        )

def multiply_rec_xhr (request):
    return multiply_rec(request,xhr=True)


def multiply_rec (request, xhr=None):
    # We can't do yields and multiplier in the same place!
    print 'MULTIPLY!'
    if request.method == 'POST':
        form = MultiplierForm(request.POST)
        if form.is_valid():
            recid = request.POST.get('rid',None)
            try:
                multiplier = form.cleaned_data['multiplier']
            except:
                yields = form.cleaned_data['yields']
                orig_yields = rd.get_rec(recid).yields
                multiplier = (yields / float(orig_yields))
            if xhr:
                rec = rd.get_rec(recid)
                d = {'yields':rec.yields * multiplier,
                     'ingredients':get_ings(recid,multiplier),
                     'multiplier':multiplier}
                return HttpResponse(
                    simplejson.dumps(d),
                    mimetype='application/javascript'
                    )
            else:
                return HttpResponseRedirect('/rec/%s/%s'%(recid,multiplier))

def shop (request, rec_id=None, mult=1):
    mult = float(mult)
    if rec_id is not None:
        slist.addRec(rd.get_rec(rec_id),mult)
    recs = slist.recs.values()
    data,pantry = slist.organize_list(slist.lst)
    #recs = [('foo',4),]
    #data = [('sugar','3 cups'),]
    #pantry = [('sugar','3 cups'),]
    return render_to_response('shop.html',{'data':data,'pantry':pantry,
                                           'recs':recs})

def shop_remove (request, rec_id=None):
    try:
        rec_id = int(rec_id)
        if slist.recs.has_key(rec_id):
            del slist.recs[int(rec_id)]
        else:
            print 'Odd, there is no ',rec_id,'on the shopping list'
    except TypeError:
        print 'Odd, rec_id',rec_id,'is the wrong type'
        raise
    return shop(request)

def shop_to_pantry (request):
    if request.method == 'POST':
        for item in request.POST:
            if item != 'submit':
                slist.sh.add_to_pantry(item)
        return HttpResponseRedirect('/shop/')

def shop_to_list (request):
    if request.method == 'POST':
        for item in request.POST:
            if item != 'submit':
                slist.sh.remove_from_pantry(item)
        return HttpResponseRedirect('/shop/')


def thumb (request, rec_id):
    return HttpResponse(rd.get_rec(rec_id).thumb,
                        mimetype='image/jpeg'
                        )

def img (request, rec_id):
    return HttpResponse(rd.get_rec(rec_id).image,
                        mimetype='image/jpeg'
                        )

gourmet/plugins/web_plugin/gourmetweb/templates/index.html
<html>
  <head>
    <style type="text/css">
      {%include "menu.css" %}
    </style>
    <style type="text/css">
      .rowhead {background: #222; color: #eee}
      .rowhead a {background: #222; color: #eef}
      .row1 {background:#ddd}
      .row2 {background:#bbb}
      .small  .category {display: none}
      .small  .cuisine {display: none}
      .tiny .category {display: none}
      .tiny  .cuisine {display: none}
      .small .title {font-size: x-large}
      .tiny .title {font-size: x-large}
    </style>
    <script type="text/javascript" src="/js/jquery.js"></script>
    <script type="text/javascript" src="/js/detect_screensize.js"></script>
    <script type="text/javascript">
      function do_search (event) {
	    $.ajax({
	    type: "POST",
	    url: "/rec/do_search_xhr/",
	    dataType: "html",
	    data: $("#search_form").serialize(),
	    success: function (data){
	    $("#reclist").html(data);
	    }
	    });
      }
      $(document).ready(function(event){
	    $("#search_form").submit(function(event){
              event.preventDefault();
              do_search(event);
              });
            $("#id_search_field").keyup(do_search);
      });


    </script>
  <body>
    {%include "menu.html"%}
    <div id="main">
    <form  id="search_form" action="/rec/do_search/" method="post">{{form.as_p}}
<input type="submit" value="search">
    </form>
    <div id="reclist">{%include "list.html" %}</div>
    </div>
  </body>
</html>

gourmet/plugins/web_plugin/gourmetweb/templates/list.html
<table>
      <tr class="rowhead"><th></th><th class="title"><a href="/sort/title/">Title</a></th><th class="cuisine"><a href="/sort/cuisine/">Cuisine</a></th><th class="category"><a href="/sort/category/">Category</a></th><th></th></tr>
	{% for r, cats in recs %}
      <tr class="{% cycle 'row1' 'row2' %}">
	<td class="thumb">{% if r.thumb %}
	  <a href="/rec/{{r.id}}/"><img src="/thumb/{{r.id}}/"></a>
	  {%endif%}
	</td>
	<td class="title"><a href="/rec/{{ r.id }}/">{{ r.title }}</a></td>
	<td class="cuisine">{{ r.cuisine }}</td>
	<td class="category">
	  -
	  {% for c in cats %}
	  {{c}}
	  -
	  {% endfor %}
	  </td>
	<td><a href="/shop/{{r.id}}/">(add to shopping list)</a></td>
      </tr>
      {% endfor %}
    </table>

gourmet/plugins/web_plugin/gourmetweb/templates/menu.html
<table id="menu">
  <tr>
    <td>Gourmet Recipe Manager - Web View</td>
    <td><a href="http://thinkle.github.io/gourmet/">Learn More</a></td>
    <td><a href="/">Recipes</a></td>
    <td><a href="/shop/">Shopping List</a></td>
  </tr>
</table>

gourmet/plugins/web_plugin/gourmetweb/templates/rec.html
<html>
  <head>
    <style type="text/css">
      {%include "menu.css" %}
      #my_multiply_form p {display: inline}
      #id_multiplier {width: 3em}
      #id_yields {width: 5em}
      #ingredients_container {position: absolute; top: 5em; right: 2em;
        border: 1px dashed #888; padding-top: 0em;
        width: 35%}
      #ingredients_container h2 {background-color: #000; color: #ccc; margin: 0em; padding: 5px; text-align: center}
      #my_multiply_form {background-color: #ccc; width: 300px; border: 1px dashed #000; padding: 1em}
      #hide_multiplier {text-align: right; float: right; margin: 0; padding: 0}
      #ingredients ul {padding-left: 1em; margin-left: 0em}
      #ingredients li {list-style-type: none; padding-left: 0em; margin-left: 0em}
      #attrs {width: 60%}
      #recimage {max-width: 60%; display: block}
      #text {width: 60%}
    </style>
    <script type="text/javascript" src="/js/jquery.js"></script>
    <script type="text/javascript">
      function do_multiply (event){
          event.preventDefault();
           $.ajax({
            type: "POST",
	    url: "/rec/multiply_xhr/",
            dataType:"json",
	    data: $("#my_multiply_form").serialize(),
            success: function (data){
             $("#ingredients").html("");
             /* var new_ingredients = "<ul>"; */
	     for (row in data.ingredients) {
	          if (data.ingredients[row][0] ) {
	          $("#ingredients").append("<h3>"+data.ingredients[row][0]+"</h2>");}
	          for (i in data.ingredients[row][1]) {
	             $("#ingredients").append("<br>"+data.ingredients[row][1][i]);
	          }
              }
              $("#yields").html(data.yields);
              $("#mult").html("(x"+data.multiplier+")");
              $("#shoprec").attr("href",
                                 "/shop/{{r.id}}/"+data.multiplier);
              $("#shoplink").html("<a href='/shop/{{r.id}}/"+data.multiplier+"'>Add to Shopping List</a>");
              }
          });
      }
      function show_multiplier (event){
        event.preventDefault();
        $("#my_multiply_form").attr("style","display:block");
        $("#show_multiplier").attr("style","display:none");
      }
      function hide_multiplier (event){
        event.preventDefault();
        $("#my_multiply_form").attr("style","display:none");
        $("#show_multiplier").attr("style","display:inline");
      }
      $(document).ready(function(event){
        $("#my_multiply_form").submit(do_multiply);
        $("#show_multiplier").click(show_multiplier);
        $("#hide_multiplier").click(hide_multiplier);
       });

    </script>
  </head>
  <body>
    {%include "menu.html"%}

    <div id="main">
      <h1>{{ r.title }}</h1> <span id="shoplink"><a href="/shop/{{r.id}}/{{mult}}">Add to Shopping List</a></span>
    {% if r.image %} <img id="recimage"  src="/img/{{r.id}}/"> {% endif %}
    <div id="attrs">
    <p><i>
    {% if r.cuisine %} <br>Cuisine: {{ r.cuisine }} {% endif %}
    {% if r.link %} <br>Original Link: <a href="{{ r.link }}">{{ r.link }}</a> {% endif %}
    {% if r.rating %} <br>Rating: {{ r.rating }} {% endif %}
    {% if cats %}<br>Categories: {{ cats }}{% endif %}
    {% if r.yields %} <br>Yields: <span id="yields">{{yields}}</span> {{r.yield_unit}} {% endif %}
    <span id="mult">{% if is_adjusted %}
      (x{{mult}})
      {% endif %}
    </span> <a id="show_multiplier" href="none">(Edit)</a>
    <form style="display:none" id="my_multiply_form" action="/rec/multiply/" method="post">
      {{ multiplier_form.as_p }}
      <input type="hidden" name="rid" value="{{ r.id }}"><input type="submit" value="Multiply">
      <a href="none" id="hide_multiplier">(close)</a>
    </form>
    </i></p></div>
    <div id="text">
    {% if r.instructions %}
    <h2>Instructions</h2>
    <p>{{ instructions|safe }}</p>
    {% endif %}
    {% if r.modifications %}
    <h2>Notes</h2>
    <p>{{ notes|safe }}</p>
    {% endif %}
    </div>

    <div id="ingredients_container">
      <h2>Ingredients</h2>
      <div id="ingredients">
    <ul>
      {% for group, items in ings %}

	{% if group %}
      <li>

	<b>{{ group }}</b>
	<ul>
	{% endif %}
	{% for item in items %}
	<li>{{ item }}</li>
	{% endfor %}
	{% if group %}
	</ul>
	</li>
	{% endif %}

      {% endfor %}
    </ul>
    </div>
    </div>
    </div>
  </body>
</html>

gourmet/plugins/web_plugin/gourmetweb/templates/shop.html
<html>
  <head>
    <script type="text/javascript" src="/js/jquery.js"></script>
    <script type="text/javascript" src="/js/detect_screensize.js"></script>
    <style type="text/css">
      {%include "menu.css" %}
      .small {color: red; background: yellow}
      .tiny {color: yellow; background: black}
    </style>
  </head>
<body>
  {%include "menu.html"%}
  <div id="main">
  <div>
    <h2>Shopping list for...</h2>
    {% for rec, mult in recs %}
    <br><a href="/rec/{{rec.id}}/">{{rec.title}}</a> x{{mult}} <a href="/shop/remove/{{rec.id}}/">(remove)</a>
    {% endfor %}
  </div>
  <table width="85%">
    <tr>
      <td valign="top" width="50%">
	<form
	   id="shopping_list_form"
	   action="/shop/to_pantry/"
	   method="post"
	   >
	<h2 style="margin-bottom:0">Shopping List </h2>
	<input type="submit" name="submit" value="Move checked items to Pantry List">

    {% for group, lst in data %}
    <h3>{{group}}</h3>
    {% for item, amt in lst %}
    <input type="checkbox" name="{{item}}">{{item}} {{amount}}</input><br>
    {% endfor %}
    {% endfor %}
    </form>
      </td>
      <td valign="top" width="50%">
	<form
	   id="pantry_list_form"
	   action="/shop/to_list/"
	   method="post"
	   >
	<h2 style="margin-bottom:0">Pantry List</h2>
	<input type="submit" name="submit" value="Move checked items to Shopping List">
	{% for group, lst in pantry %}
    <h3>{{group}}</h3>
    {% for item, amt in lst %}
    <input type="checkbox" name="{{item}}">{{item}} {{amount}}<br></input>
    {% endfor %}
    {% endfor %}
      </td>
    </tr>
  </table>
  </div>
</body>
</html>